declare type SegmentEvents = 'Page Viewed' | 'Registration Completed' | 'Registration Started'
declare type SegmentTrackProtocol<E extends SegmentEvents> = E extends 'Page Viewed' ? PageViewed : E extends 'Registration Completed' ? RegistrationCompleted : E extends 'Registration Started' ? RegistrationStarted : never;
declare type SegmentTrackProtocolUnion = {event: 'Page Viewed', properties: PageViewed } | {event: 'Registration Completed', properties: RegistrationCompleted } | {event: 'Registration Started', properties: RegistrationStarted }/* tslint:disable */
/**
* This file was automatically generated by json-schema-to-typescript.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run json-schema-to-typescript to regenerate this file.
*/

declare interface PageViewed {
page_url?: string
page_name?: string

}
